### ISSUE TITLE
M1.1 End of VIRCAM observing on VISTA

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#320]

**Comment by wfastrononomer** [comment]
Message from Boris Haussler (ESO), on 8th March 2023
Dear all,
(@DSC, please forward to the survey TIOs, I do not have their email list)
 
As you might know, sunday night was the last night of (scientific) VIRCAM observations. While it will be used for the VISTA preparation for 4MOST, no more scientific data will be taken.
 
As such, I would like to take the opportunity to thank everyone for the last 14 years of operations and the effort they have put in to make it a success.
VIRCAM has amassed more than 40000 hours of observing time. A great achievement by any account!
This is due to the entire IOT and the hard work they have put in over the years, and the TIOs who have dutifully carried out the observations every night.
 
 
So Thank you everybody for the effort, I will wrap up the decommissioning and then the IOT will be dissolved soon.
 
 
Below, I attach a similar message from Bo Milvang-Jensen, one of the survey PIs (UltraVISTA), which I thought was worth sharing.
 
For those interested: We are organizing a workshop to celebrate VIRCAM and OmegaCam, which will take place in Garching:
"A Decade of ESO Wide-field Imaging Surveys"
16 October 2023 - 20 October 2023
 
Lastly, here you can find a time-lapse of VIRCAMs last night (not a great one as you can see from the clouds), and the VISTA dome closing one last time for VIRCAM science observations.
https://www.dropbox.com/s/qzcfvwc1qey35kn/2023_03_05_VISTA_last_night_HQ.mp4?dl=0
 
 
Thanks you,
Boris
