### ISSUE TITLE
Create test plan/ Python test suite

### ISSUE THREAD

**Issue by tms-epcc** [wfau/ScienceArchives#441]

**Comment by tms-epcc** [comment]
04/OCT/23
- need @MikeeRead to provide a list of queries

**Comment by tms-epcc** [comment]
24/OCT/23
- created a library to compare two TAP services 
- this works subject to a few more minor changes and checks

**Comment by tms-epcc** [comment]
07/NOV/23 
- Repo is https://github.com/stvoutsin/tapvalidator

**Comment by tms-epcc** [comment]
20/NOV/3
- still to do the above actions

**Comment by stvoutsin** [comment]
Update:
I've checked the decimal point issue mentioned above, and the following query:

`SELECT AVG(rAperMag3) FROM ATLASDR1.atlasSource WHERE rAperMag3 > 0.0
`
produces a result that differs very slightly due to rounding (13th decimal place):
SQL Server direct query: 20.8584454525599
TAP query: 20.85844545255986

**Comment by stvoutsin** [comment]
I've also now extended the validator to run a query to one of the tables on each databases. (SELECT TOP 10 * FROM ..)

**Comment by tms-epcc** [comment]
11/JAN/24
- Validator is written and running see https://github.com/stvoutsin/tapvalidator/
- runs every hour and reports issues to Slack
- this ticket can be closed 
- updating the test suite is now part of the development process 
- any new items for this will be in new tickets and reviewed as necessary
