### ISSUE TITLE
Add team generated catalogues to the release.

### ISSUE THREAD

**Issue by wfastrononomer** [wfau/ScienceArchives#495]
The VMC team are producing a set of data products for this final release.

Expected products:
RR Lyrae (downloaded) - Schema updating

PSFs - in /disk63. LMC_3_4 is newer and not unzipped. Have these had the 1.3_1.5 photometric shifts applied. Are they already in the VSA? Are the shifts the correct ones?

Proper motion - Need a schema

++
Clara Pennock - Machine Learning classifications sent files and description. Will download and set up. Setup - done SMC, but not LMC yet.

Mostly in VSA, but need to run cu19.

**Comment by wfastrononomer** [comment]
Need to add the data to /disk62/sys/ExternalProducts/teamCats/VMC
Need to add/update VSA_vmcTeamCatalogueSchema
Need to run invocations/cu29/ConvertTeamCats.py

Might need to make changes. E.g. linking the PM catalogue to the PSF catalogue rather than to the Source table - new options.

**Comment by tms-epcc** [comment]
08/MAY/24
@wfastrononomer reported
- added machine learning classification : found a column combination bug while doing this and fixed it.  This had meant that the last column that entered the table was being used instead of the correct column
- added propermotion lmc only but needs some improvements for psf first. Also needs smc
- currently working on rrlyrae variable stars just now

**Comment by tms-epcc** [comment]
05/JUN/24
- added neighbour tables too 
- this is done
